exports.USER_ROLE = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
};

exports.PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PENDING",
};

exports.ORDER_STATUS = {
  PAYMENTSUCESSFUL: "PAYMENTSUCESSFUL",
  PROCESSING: "PROCESSING",
  OUTFORDELIVERY: "OUTFORDELIVERY",
  DELIVERED: "DELIVERED",
};

exports.DEPARTMENT = {
  PRODUCTS: "PRODUCTS",
  LIVINGROOM: "LIVINGROOM",
  DININGROOM: "DININGROOM",
  BEDROOM: "BEDROOM",
  WORKSPACE: "WORKSPACE",
  OUTDOOR: "OUTDOOR",
};

exports.CATEGORY_TYPE = {
  SEATING: "SEATING",
  TABLES: "TABLES",
  BEDANDMATTRESSES: "BEDANDMATTRESSES",
  OFFICE: "OFFICE",
  OUTDOOR: "OUTDOOR",
  LIGHTING: "LIGHTING",
  OFFICECHAIRS: "OFFICECHAIRS",
  OFFICEDESKS: "OFFICEDESKS",
};
